[theme]
primaryColor = "#8b5cf6"
backgroundColor = "#07070f"
secondaryBackgroundColor = "#11111f"
textColor = "#e9eaf6"
font = "sans serif"
base = "dark"

[server]
headless = true
fileWatcherType = "none"

[browser]
gatherUsageStats = false
